# Generated by Django 5.2 on 2025-04-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.skill', verbose_name='Skill'),
        ),
    ]
