# Generated by Django 5.2 on 2025-04-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skill',
            new_name='Skill',
        ),
    ]
