<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skill',
            new_name='Skill',
        ),
    ]
=======
# Generated by Django 5.2 on 2025-04-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skill',
            new_name='Skill',
        ),
    ]
>>>>>>> 923b7e74aa52c6ad7c42b9ea8d038dfd98d71b79
