# Generated by Django 5.2 on 2025-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_skill_user_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Skill',
            new_name='skill',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
