# Generated by Django 5.2 on 2025-04-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
