# Generated by Django 5.2 on 2025-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_skill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
    ]
